databases:
  - name: postgres
    ipAllowList: []
    databaseName: recipe_manager
    user: recipe_manager

services:
  - type: web
    name: recipe-manager
    plan: free
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false